# Site settings
title: "Asher Cole | Engineering Portfolio"
description: "Portfolio of engineering projects and professional experience"
baseurl: ""
url: "https://AsherCole1.github.io"
repository: AsherCole1/AsherCole1.github.io

# Minimal Mistakes via GitHub Pages
remote_theme: "mmistakes/minimal-mistakes"

# Plugins (required)
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

# Fonts
fonts:
  header: "Roboto Slab"
  body: "Roboto"

# Markdown
markdown: kramdown
kramdown:
  input: GFM
